version: '3'
services:
  in-memory-gremlin-server:
    image: tinkerpop/gremlin-server:3.6.2
    ports:
      - "8182:8182"
    volumes:
      - .docker/gremlin-server/:/custom-gremlin/

  in-memory-populate:
    image: tinkerpop/gremlin-console:3.4.10
    depends_on:
      - in-memory-gremlin-server
    volumes:
      - .docker/gremlin-console/:/custom-gremlin/
      - .docker/gremlin-console/conf/remote-memory.yaml:/opt/gremlin-console/conf/remote.yaml
    entrypoint: sh -c "sleep 5 && ulimit -n 65535 && bin/gremlin.sh -i /custom-gremlin/resources/init-in-memory.groovy"

  recommendation:
    build:
      context: .
    ports:
      - "5000:8080"
    environment:
      - GREMLIN_HOST=in-memory-gremlin-server
    depends_on:
      in-memory-populate:
        condition: service_completed_successfully
